In [10]:
import numpy as np

In [54]:
a=np.array([0,10,20,30]).reshape((4,1))
b=np.array([0,1,2,3,4])
a+b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

Транспонировать массив a можно также с помощью следующей команды:

In [56]:
np.array([0,10,20,30])[:,np.newaxis]

array([[ 0],
       [10],
       [20],
       [30]])

# Задание 2

Размерность будет 1х5, т.к -1 элемент индекса равен размерности вектора, т.е 5

In [49]:
np.arange(5).reshape(1,-1)

array([[0, 1, 2, 3, 4]])

Здесь размерность будет уже 5х1

In [51]:
np.arange(5).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

Размерность суммы будет равна 5х5, т.к сначала массив 1х5 расширяется до 5х5, а затем второй массив расширяет число столбцов до 5:

In [58]:
np.arange(5).reshape(1,-1)+np.arange(5).reshape(-1,1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])