In [2]:
import numpy as np

# Задание 1.

Создаем одномерный массив от 0 до 3 и делаем из него двумерный.

In [161]:
a = np.arange(4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

Попробуем прибавить к каждому элементу массива 0.5

In [162]:
a += 0.5

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

Данные ошибка говорит о том, что массив, элементы которого будут в результате сложения иметь тип float64, не может быть записан в переменную, в которой был записан массив типа int32

# Задание 2.

In [3]:
a = np.array( [0, 10, 20, 30] ).reshape( (4, 1) )
b = np.array( [0, 1, 2, 3, 4] )
a + b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

Транспонировать массив a можно также с помощью следующей команды:

In [4]:
np.array( [0, 10, 20, 30] )[:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30]])

# Задание 3.

Размерность будет 1х5, т.к -1 элемент индекса равен размерности вектора, т.е 5

In [5]:
np.arange(5).reshape(1, -1)

array([[0, 1, 2, 3, 4]])

Здесь размерность будет уже 5х1

In [6]:
np.arange(5).reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

Размерность суммы будет равна 5х5, т.к сначала массив 1х5 расширяется до 5х5, а затем второй массив расширяет число столбцов до 5:

In [7]:
np.arange(5).reshape(1, -1) + np.arange(5).reshape(-1, 1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

# Задание 4.

Создаем нулевую матрицу 8х8

In [9]:
chess = np.zeros( (8,8) )
chess

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

Заполняем матрицу единицами через один элемент исходной нулевой матрицы

In [11]:
chess[0::2, 0::2] = 1
chess[1::2, 1::2] = 1
chess

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# Задание 5.

Создаем вектор с компонентами от 0 до 5

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

Вставляем через 1 элемент с помощью команды insert нули

In [34]:
np.insert( a, a[1::], 0 ) 

array([0, 0, 1, 0, 2, 0, 3, 0, 4])

# Задание 6.

Создадим массив 3х3 чисел от 0 до 9

In [154]:
a = np.random.randint( 10, size= (3, 3) )
a

array([[5, 6, 4],
       [2, 3, 1],
       [9, 9, 0]])

Для того, чтобы найти номера строк, соответсвующих упорядоченному по возрастанию первому второму столбцу, используем функцию argsort.
<br>
Для сортировки просто передаем полученный в результате argsort массив индексов в качестве индекса исходной матрицы a.

In [155]:
a[ np.argsort( a[:, 1] ) ]

array([[2, 3, 1],
       [5, 6, 4],
       [9, 9, 0]])

# Задание 7.

Создаем двумерный массив чисел от 0 до 9

In [143]:
a = np.random.randint( 10, size= (2, 2) )
a

array([[9, 9],
       [9, 5]])

Используем стандартную питоновскую схему перестановки двух переменных
<br>
Сначала инициализируется кортеж из правой части - вторая строка и копия первой (чтобы не получились в результате две одинаковые строчки). Затем левая часть, а затем каждому элементу обоих кортежей присваиваются соответствующие значения

In [144]:
a[0,:],a[1, :] = a[1, :],a[0, :].copy()
a

array([[9, 5],
       [9, 9]])

# Задание 8.

Создаем двумерный массив случайный чисел из интевала (0,255)

In [146]:
a = np.random.randint( 255, size = (2,2) )
a

array([[ 99, 127],
       [ 91,  34]])

С помощью argmax мы можем найти индекс максимального элемента матрицы, но ее одномерного плоского представления.
<br>
Между "плоским" индексом и исходным двумерным индексом в памяти есть линейная связь.
<br>
Поэтому двумерный индекс мы можем восстановить с помощью команды unravel_index, которой нужно передать размерность двумерного массива и "плоский" индекс.

In [147]:
ind_max = np.unravel_index( np.argmax(a), a.shape )
ind_max

(0, 1)

Далее присваиваем максимальному элементу матрицы среднее по матрице, вычисленное с помощью mean

In [148]:
a[ ind_max ]=np.mean(a)
a

array([[99, 87],
       [91, 34]])

# Задание 9.

Создаем одномерный массив из 10 чисел от 0 до 255.

In [169]:
section = np.random.randint( 255,size = 10 )
section

array([149, 187, 205, 178, 163, 155,  45,  82, 225, 212])

Для линейного отображения вычтем из каждого элемента массива минимальный элемент и разделим на разность максимального и минимального элемента.
<br>
Так минимальный элемент перейдет в 0, максимальный - в 1, а все остальные элементы - в интервал (0,1).

In [168]:
( section - section.min() ) / ( section.max() - section.min() )

array([0.00966184, 0.37198068, 1.        , 0.16425121, 0.65217391,
       0.70531401, 0.14975845, 0.13043478, 0.        , 0.53140097])