In [2]:
import numpy as np

# Задание 1.

Создаем одномерный массив от 0 до 3 и делаем из него двумерный.

In [161]:
a = np.arange(4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

Попробуем прибавить к каждому элементу массива 0.5

In [162]:
a += 0.5

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

Данные ошибка говорит о том, что массив, элементы которого будут в результате сложения иметь тип float64, не может быть записан в переменную, в которой был записан массив типа int32

# Задание 2.

In [3]:
a = np.array( [0, 10, 20, 30] ).reshape( (4, 1) )
b = np.array( [0, 1, 2, 3, 4] )
a + b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

Транспонировать массив a можно также с помощью следующей команды:

In [4]:
np.array( [0, 10, 20, 30] )[:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30]])

# Задание 3.

Размерность будет 1х5, т.к -1 элемент индекса равен размерности вектора, т.е 5

In [5]:
np.arange(5).reshape(1, -1)

array([[0, 1, 2, 3, 4]])

Здесь размерность будет уже 5х1

In [6]:
np.arange(5).reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

Размерность суммы будет равна 5х5, т.к сначала массив 1х5 расширяется до 5х5, а затем второй массив расширяет число столбцов до 5:

In [7]:
np.arange(5).reshape(1, -1) + np.arange(5).reshape(-1, 1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

# Задание 4.

Создаем нулевую матрицу 8х8

In [9]:
chess = np.zeros( (8,8) )
chess

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

Заполняем матрицу единицами через один элемент исходной нулевой матрицы

In [11]:
chess[0::2, 0::2] = 1
chess[1::2, 1::2] = 1
chess

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# Задание 5.

Создаем вектор с компонентами от 0 до 5

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

Вставляем через 1 элемент с помощью команды insert нули

In [34]:
np.insert( a, a[1::], 0 ) 

array([0, 0, 1, 0, 2, 0, 3, 0, 4])

# Задание 6.

Создадим массив 3х3 чисел от 0 до 9

In [154]:
a = np.random.randint( 10, size= (3, 3) )
a

array([[5, 6, 4],
       [2, 3, 1],
       [9, 9, 0]])

Для того, чтобы найти номера строк, соответсвующих упорядоченному по возрастанию первому второму столбцу, используем функцию argsort.
<br>
Для сортировки просто передаем полученный в результате argsort массив индексов в качестве индекса исходной матрицы a.

In [155]:
a[ np.argsort( a[:, 1] ) ]

array([[2, 3, 1],
       [5, 6, 4],
       [9, 9, 0]])

# Задание 7.

Создаем двумерный массив чисел от 0 до 9

In [143]:
a = np.random.randint( 10, size= (2, 2) )
a

array([[9, 9],
       [9, 5]])

Используем стандартную питоновскую схему перестановки двух переменных
<br>
Сначала инициализируется кортеж из правой части - вторая строка и копия первой (чтобы не получились в результате две одинаковые строчки). Затем левая часть, а затем каждому элементу обоих кортежей присваиваются соответствующие значения

In [144]:
a[0,:],a[1, :] = a[1, :],a[0, :].copy()
a

array([[9, 5],
       [9, 9]])

# Задание 8.

Создаем двумерный массив случайный чисел из интевала (0,255)

In [146]:
a = np.random.randint( 255, size = (2,2) )
a

array([[ 99, 127],
       [ 91,  34]])

С помощью argmax мы можем найти индекс максимального элемента матрицы, но ее одномерного плоского представления.
<br>
Между "плоским" индексом и исходным двумерным индексом в памяти есть линейная связь.
<br>
Поэтому двумерный индекс мы можем восстановить с помощью команды unravel_index, которой нужно передать размерность двумерного массива и "плоский" индекс.

In [147]:
ind_max = np.unravel_index( np.argmax(a), a.shape )
ind_max

(0, 1)

Далее присваиваем максимальному элементу матрицы среднее по матрице, вычисленное с помощью mean

In [148]:
a[ ind_max ]=np.mean(a)
a

array([[99, 87],
       [91, 34]])

# Задание 9.

Создаем одномерный массив из 10 чисел от 0 до 255.

In [169]:
section = np.random.randint( 255,size = 10 )
section

array([149, 187, 205, 178, 163, 155,  45,  82, 225, 212])

Для линейного отображения вычтем из каждого элемента массива минимальный элемент и разделим на разность максимального и минимального элемента.
<br>
Так минимальный элемент перейдет в 0, максимальный - в 1, а все остальные элементы - в интервал (0,1).

In [168]:
( section - section.min() ) / ( section.max() - section.min() )

array([0.00966184, 0.37198068, 1.        , 0.16425121, 0.65217391,
       0.70531401, 0.14975845, 0.13043478, 0.        , 0.53140097])

# Задание 10.

Создадим массив целых чисел и зададим им тип float, т.к np.nan можно присвоить только элементам массива типа float.

In [38]:
nan_ar r= np.random.randint( 255, size = (8, 8) ).astype(float)
nan_arr

array([[ 43., 145., 142.,  57.,  85., 113., 184.,  12.],
       [168.,  48.,  66.,   7., 242., 212.,  15.,  93.],
       [ 59.,  77., 136.,   3.,   8., 251., 160., 167.],
       [225., 121., 112., 122.,  79., 207., 121., 128.],
       [162., 149.,  81.,  95., 161., 109.,  92., 156.],
       [210.,  27.,  19.,  80., 210., 129., 166.,  95.],
       [ 53., 225.,  19.,  66., 227., 238., 237., 108.],
       [228., 110.,  40.,  42., 221., 133., 155., 101.]])

C помощью следующей команды мы возьмем 10 различных элементов (replace=False) из нашего "плоского массива" (nan_arr.size) и сделаем их nan.

In [39]:
nan_arr.ravel()[ np.random.choice( nan_arr.size, 10, replace=False ) ] = np.nan
nan_arr

array([[ 43., 145.,  nan,  57.,  85., 113., 184.,  12.],
       [ nan,  48.,  nan,  nan, 242., 212.,  15.,  93.],
       [ 59.,  77., 136.,   3.,   8., 251., 160., 167.],
       [225., 121., 112., 122.,  79., 207., 121., 128.],
       [162., 149.,  81.,  95., 161.,  nan,  92., 156.],
       [210.,  27.,  nan,  80., 210., 129., 166.,  95.],
       [ nan,  nan,  19.,  66., 227., 238., 237., 108.],
       [ nan, 110.,  40.,  42.,  nan, 133., 155., 101.]])

Используем команду nan.nanmean, которая вычислит среднее в каждом столбце, игнорируя nan. np.round делается для того, чтобы матрица была более приятной глазу.

In [40]:
nans = np.round( np.nanmean( nan_arr, axis=1 ) )
nans

array([ 91., 122., 108., 139., 128., 131., 149.,  97.])

Определим индексы nan-элементов в нашей матрице.

In [41]:
inds = np.where( np.isnan( nan_arr ) )
inds

(array([0, 1, 1, 1, 4, 5, 6, 6, 7, 7], dtype=int64),
 array([2, 0, 2, 3, 5, 2, 0, 1, 0, 4], dtype=int64))

С помощью команды np.take сопоставим элемент из nans и индекс столбца, в котором этот элемент заменит все nan.
<br>
Затем полученный массив индексов передадим нашей матрице nan_arr.

In [42]:
nan_arr [ inds ] = np.take( nans, inds[1] )
nan_arr

array([[ 43., 145., 108.,  57.,  85., 113., 184.,  12.],
       [ 91.,  48., 108., 139., 242., 212.,  15.,  93.],
       [ 59.,  77., 136.,   3.,   8., 251., 160., 167.],
       [225., 121., 112., 122.,  79., 207., 121., 128.],
       [162., 149.,  81.,  95., 161., 131.,  92., 156.],
       [210.,  27., 108.,  80., 210., 129., 166.,  95.],
       [ 91., 122.,  19.,  66., 227., 238., 237., 108.],
       [ 91., 110.,  40.,  42., 128., 133., 155., 101.]])

# Задание 11.

In [83]:
zero_arr = np.random.randint( 255, size = ( 8, 8 ) )
zero_arr

array([[248, 115,  59, 216, 136,  59, 246,  37],
       [166,  50,  12, 107, 253,  57,  46,  67],
       [210,  21, 184,   8, 156,  73,  93, 108],
       [230, 159,  55,  62, 251, 127,   0, 235],
       [244, 240,  85,  17, 220,  75, 128, 194],
       [ 89, 153,  98,  56, 187,  74, 168,  12],
       [253,  52, 117, 249, 185,  12,  69, 156],
       [207,  15, 126, 117, 168, 208, 194,  98]])

Выберем случайное число от 0 до 8.

In [84]:
random_col = np.random.choice(8)

Запомним случайный столбец нулями.

In [85]:
zero_arr [ :, random_col ] = 0
zero_arr

array([[248,   0,  59, 216, 136,  59, 246,  37],
       [166,   0,  12, 107, 253,  57,  46,  67],
       [210,   0, 184,   8, 156,  73,  93, 108],
       [230,   0,  55,  62, 251, 127,   0, 235],
       [244,   0,  85,  17, 220,  75, 128, 194],
       [ 89,   0,  98,  56, 187,  74, 168,  12],
       [253,   0, 117, 249, 185,  12,  69, 156],
       [207,   0, 126, 117, 168, 208, 194,  98]])

Для поиска полностью нулевого столбца воспользуемся командой np.any: она вернет True, если будет хоть один ненулевой элемент в стоблце.
<br>
Нам нужно взять False с помощью логического отрицания ~.
<br>
Номер столбца найдем с помощью команды np.where.

In [86]:
np.where( ~zero_arr.any( axis = 0 ) )[0][0]

1

In [87]:
print('В матрице есть полностью нулевой столбец под номером ', np.where( ~zero_arr.any( axis = 0 ) )[0][0])

В матрице есть полностью нулевой столбец под номером  1


# Задание 12.

Создадим две матрицы 4 на 4 с элементами от 0 до 9.

In [121]:
x = np.random.randint( 10, size = ( 4, 4 ) )
y = np.random.randint( 10, size = ( 4, 4 ) )

Добавим в матрицу-делитель нулевой элемент.

In [122]:
random_col = np.random.choice( 4 )
random_row = np.random.choice( 4 )
random_row, random_col

(1, 0)

In [123]:
y [ random_row, random_col ] = 0

С помощью команды np.divide разделим одну матрицу на другую. Заменяем на 0 результат деления на 0, также заменяем на 0 np.nan, который появляется в результате деления нуля на ноль.

In [137]:
div = np.divide( x, y )
div [ div == np.inf ] = 0
div [ np.isnan(div) ] = 0
div

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.8       , 0.        , 0.        , 1.        ],
       [0.        , 3.        , 1.        , 1.5       ],
       [9.        , 0.4       , 1.16666667, 0.        ],
       [0.        , 1.6       , 1.        , 0.4       ]])

# Задание 13.

Создадим нужные нам по условию задачи массивы.

In [8]:
x = np.ones( 10 )
i = np.array( [ 0, 1, 2, 3, 5, 5, 5, 8] ) 

Команда np.add.at аналогична команде x[i]+=1, только для повторяющихся индексов прибавит столько единиц, сколько было индексов.

In [9]:
np.add.at( x, i, 1 )
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

# Задание 14.

Создадим нужные нам массивы.

In [10]:
x = np.array( [1, 2, 3, 4] )
y = np.array( [5, 6, 7, 8] )

Создадим массив пар с помощью команды np.stack.

In [23]:
np.stack( (x, y), axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Задание 15.